# Generated by Django 4.0.3 on 2022-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_remove_project_summary_project_sprint_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.TextField(default='default title'),
            preserve_default=False,
        ),
    ]
