# Generated by Django 4.0.3 on 2022-05-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_alter_project_sprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='password',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'In Progress'), (2, 'Finished')], null=True),
        ),
    ]
