# Generated by Django 4.0.3 on 2022-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_project_password_sprint_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'To Start'), (2, 'In Progress'), (3, 'Finished')], null=True),
        ),
    ]
