# Generated by Django 4.0.3 on 2022-05-31 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrum', '0006_alter_sprint_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_for',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_for',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by+', to=settings.AUTH_USER_MODEL),
        ),
    ]
