# Generated by Django 4.0.3 on 2022-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_remove_task_assigned_for_task_assigned_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Finished')], null=True),
        ),
    ]
